name: Places
main: net.preoccupied.bukkit.places.PlacesPlugin
version: 0.2
author: obriencj@gmail.com
database: true
description: Location-based graveyards, world-specific homes and spawns, and place naming.

commands:
  home:
    description:
    usage: /home
    aliases: [h, ]
    permission: preoccupied.places.home

  set-home:
    description:
    usage: /set-home
    aliases: [sethome, ]
    permission: preoccupied.places.home

  visit:
    description: Teleports to another player
    usage: /visit PLAYER_NAME
    aliases: [v, ]
    permission: preoccupied.places.visit

  visit-place:
    description: Teleports to a place
    usage: /visit-place [WORLD] PLACENAME
    permission: preoccupied.places.visitplace
    
  graveyard:
    description:
    usage: /graveyard
    aliases: [gy, ]
    permission: preoccupied.places.graveyard

  invite:
    description: Invites a player to teleport to your current location
    usage: /invite PLAYER_NAME
    aliases: [inv, ]
    permission: preoccupied.places.invite

  accept:
    description: Accepts an invitation, teleporting to the invite location
    usage: /accept
    permission: preoccupied.places.accept
    
  return:
    description: Undoes previous /visit, /visit-place, /home, /graveyard, /accept, or /spawn
    usage: /return
    aliases: [r, ]
    permission: preoccupied.places.return

  spawn:
    description: Goes to the world spawn place
    usage: /spawn
    permission: preoccupied.places.spawn

  set-spawn:
    description: Set the world spawn
    usage: /set-spawn
    aliases: [setspawn, ]
    permission: preoccupied.places.setspawn
    
  add-place:
    description: Creates a new place and optionally sets its weight and title
    usage: /add-place PLACE_NAME [WEIGHT [TITLE]]
    permission: preoccupied.places.edit

  remove-place:
    description: Removes a place
    usage: /remove-place PLACE_NAME
    permission: preoccupied.places.edit

  set-place-weight:
    description: Sets the weight for a place
    usage: /set-place-weight PLACE_NAME WEIGHT
    aliases: [set-place-radius, ]
    permission: preoccupied.places.edit

  set-place:
    description: Sets the center and optionally the weight for a place
    usage: /set-place PLACE_NAME [WEIGHT]
    permission: preoccupied.places.edit

  set-place-entrance:
    description: Sets the entrance for a place
    usage: /set-place-entrance PLACE_NAME
    permission: preoccupied.places.edit
    
  set-place-graveyard:
    description: Sets the graveyard for a place
    usage: /set-place-graveyard PLACE_NAME
    aliases: [set-place-gy, ]
    permission: preoccupied.places.edit

  clear-place-graveyard:
    description: Removes the graveyard from a place
    usage: /clear-place-graveyard PLACE_NAME
    aliases: [unset-place-graveyard, unset-place-gy, ]
    permission: preoccupied.places.edit
    
  set-place-title:
    description: Sets or clears the title for a place
    usage: /set-place-title PLACE_NAME [TITLE]
    permission: preoccupied.places.edit

  find-place:
    description: Prints the list of places on a world
    usage: /find-place [WORLD] PATTERN
    permission: preoccupied.places.info
    
  place-info:
    description: Prints information about a place
    usage: /place-info [WORLD] PLACE_NAME
    permission: preoccupied.places.info
    
  whereis:
    description:
    usage: /whereis PLAYER_NAME
    permission: preoccupied.places.whereis

  whereami:
    description:
    usage: /whereami
    permission: preoccupied.places.whereami

  nearby:
    description:
    usage: /nearby
    permission: preoccupied.places.nearby

  jail:
    description: Sends a player to Jail
    usage: /jail PLAYER_NAME [MINUTES]
    permission: preoccupied.places.jail

  unjail:
    description: Releases a player from Jail
    usage: /unjail PLAYER_NAME
    permission: preoccupied.places.jail

  resurrect:
    description: Return player (or yourself) to the location of their recent demise.
    usage: /resurrect [PLAYER_NAME]
    aliases: [undie, rez]
    permission: preoccupied.places.resurrect


permissions:
  preoccupied.places.admin:
    description: Admin permissions
    default: op
    children:
      preoccupied.places.home: true
      preoccupied.places.visit: true
      preoccupied.places.visitplace: true
      preoccupied.places.graveyard: true
      preoccupied.places.spawn: true
      preoccupied.places.invite: true
      preoccupied.places.accept: true
      preoccupied.places.return: true
      preoccupied.places.bring: true
      preoccupied.places.setspawn: true
      preoccupied.places.edit: true
      preoccupied.places.info: true
      preoccupied.places.whereis: true
      preoccupied.places.whereami: true
      preoccupied.places.nearby: true
      preoccupied.places.jail: true
      preoccupied.places.resurrect: true

  preoccupied.places.advanced:
    description: Advanced users
    default: false
    children:
      preoccupied.places.home: true
      preoccupied.places.visit: true
      preoccupied.places.visitplace: true
      preoccupied.places.graveyard: true
      preoccupied.places.spawn: true
      preoccupied.places.invite: true
      preoccupied.places.accept: true
      preoccupied.places.return: true
      preoccupied.places.edit: true
      preoccupied.places.info: true
      preoccupied.places.whereami: true
      preoccupied.places.whereis: true
      preoccupied.places.nearby: true
      preoccupied.places.resurrect: true

  preoccupied.places.member:
    description: Normal users
    default: false
    children:
      preoccupied.places.home: true
      preoccupied.places.spawn: true
      preoccupied.places.accept: true
      preoccupied.places.return: true
      preoccupied.places.whereami: true
      
  preoccupied.places.home:
    default: false

  preoccupied.places.visit:
    default: false

  preoccupied.places.graveyard:
    default: false

  preoccupied.places.spawn:
    default: false

  preoccupied.places.invite:
    default: false

  preoccupied.places.accept:
    default: false
    
  preoccupied.places.return:
    default: false

  preoccupied.places.bring:
    default: false
    
  preoccupied.places.setspawn:
    default: false

  preoccupied.places.edit:
    default: false

  preoccupied.places.info:
    default: false
    
  preoccupied.places.whereis:
    default: false

  preoccupied.places.whereami:
    default: false

  preoccupied.places.nearby:
    default: false

  preoccupied.places.jail:
    default: false

  preoccupied.places.resurrect:
    default: false
    
    

# The end.
